config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post 'home/skill_up', :as => 'skill_up'

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/user_skill_up.rb
class UserSkillUp
  def initialize(user, params)
    @user = user
    @params = params
  end
  def skill_up
    if params_valid?
      ActiveRecord::Base.transaction do
        if character_xp_present?
          @user.update(xp: @params[:character_xp].to_i)
        end
        if character_strength_present?
          @user.update(strength: @params[:character_strength].to_i)
        end
        if character_agility_present?
          @user.update(agility: @params[:character_agility].to_i)
        end
        if character_stamina_present?
          @user.update(stamina: @params[:character_stamina].to_i)
        end
        'skills update'
      end
    else
      'invalid params'
    end
  end

  def params_valid?
    # this method summarizes the passed params and compare them to user fields
    require_value = 0
    real_value = 0
    if character_xp_present?
      require_value += @params[:character_xp].to_i
      real_value += @user.xp.to_i
    end
    if character_strength_present?
      require_value += @params[:character_strength].to_i
      real_value += @user.strength.to_i
    end
    if character_agility_present?
      require_value += @params[:character_agility].to_i
      real_value += @user.agility.to_i
    end
    if character_stamina_present?
      require_value += @params[:character_stamina].to_i
      real_value += @user.stamina.to_i
    end
    require_value == real_value
  end

  def character_xp_present?
    @params[:character_xp].to_i != 0
  end

  def character_strength_present?
    @params[:character_strength].to_i != 0
  end

  def character_agility_present?
    @params[:character_agility].to_i != 0
  end

  def character_stamina_present?
    @params[:character_stamina].to_i != 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def skill_up
    UserSkillUp.new(current_user, params).skill_up
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.haml
%h1 welcom!
You logen as
= current_user.email

= form_tag(skill_up_path, method: 'post') do
  %h3 character stats:
  xp:
  = label_tag( :character_xp, current_user.xp, class: 'character_xp')
  = hidden_field_tag(:character_xp)
  %div{class: 'row'}
    %div{class: 'col-md-2'}
      strength:
      %span{class: 'character_strength'}
        = current_user.strength
    = hidden_field_tag(:character_strength)
    %div{class: 'col-md-10'}
      = link_to '', '#', class: 'btn btn-default glyphicon glyphicon-plus  increment', id: 'character_strength', remote: true
      = link_to '', '#', class: 'btn btn-default glyphicon glyphicon-minus decrement', id: 'character_strength', remote: true

    %div{class: 'col-md-2'}
      agility:
      %span{class: 'character_agility'}
        = current_user.agility
    = hidden_field_tag(:character_agility)
    %div{class: 'col-md-10'}
      = link_to '', '#', class: 'btn btn-default glyphicon glyphicon-plus increment', id: 'character_agility', remote: true
      = link_to '', '#', class: 'btn btn-default glyphicon glyphicon-minus decrement', id: 'character_agility', remote: true

    %div{class: 'col-md-2'}
      stamina:
      %span{class: 'character_stamina'}
        = current_user.stamina
    = hidden_field_tag(:character_stamina)
    %div{class: 'col-md-10'}
      = link_to '', '#', class: 'btn btn-default glyphicon glyphicon-plus increment', id: 'character_stamina', remote: true
      = link_to '', '#', class: 'btn btn-default glyphicon glyphicon-minus decrement', id: 'character_stamina', remote: true

    %div{class: 'col-md-2'}
      %br
      = submit_tag 'Submit'

app/views/layouts/application.haml
!!!
%html
  %head
    %title SkillsUp
    = stylesheet_link_tag :application, media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag :application, 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %div{class: 'container'}
      = yield